sitegroup: mysite_fi

deploy_tasks:
  development:
    before_deploy:
      - mkdir -p -m 770 files files_private
      - make build-testing
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb
      - cd $AMAZEEIO_WEBROOT && drush -y cim
      - cd $AMAZEEIO_WEBROOT && drush -y cr
      - cd $AMAZEEIO_WEBROOT && drush status
  production:
    before_deploy:
      - mkdir -p -m 770 ~/shared/files ~/shared/files_private
      - make build-production
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb
      - cd $AMAZEEIO_WEBROOT && drush -y cim
      - cd $AMAZEEIO_WEBROOT && drush -y cr
      - cd $AMAZEEIO_WEBROOT && drush status

shared:
  production:
    - src: files
      dst: public/sites/default/files

versions:
  node: 8
